load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "rules_7zip",
    strip_prefix = "rules_7zip-03a10b5796eac0aed122cf52064ed15785610857",
    urls = ["https://github.com/zaucy/rules_7zip/archive/03a10b5796eac0aed122cf52064ed15785610857.zip"],
    sha256 = "7c7d8c67e9cbb5d0c8efc269f468b807873416dac0eb4b7ebd3cf802c3af11bd",
)

load("@rules_7zip//:setup.bzl", "setup_7zip")

setup_7zip()

local_repository(
    name = "com_github_zaucy_rules_vulkan",
    path = "../",
)

load("@com_github_zaucy_rules_vulkan//:repo.bzl", "vulkan_repos")

vulkan_repos()
